version: "3.3"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    restart: always # because it is routing traffic to our entire app
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    volumes: 
      - $PWD/nginx/certs/prod:/etc/nginx/certs
      - $PWD/nginx/upstream.conf:/etc/nginx/conf.d/upstream.conf
    networks:
      - modu-network
  app:
    build: .
    ports:
      - '8080:80'
    networks:
      - modu-network

networks:
  modu-network:
    driver: bridge